### ISSUE TITLE
TypeError: write() takes exactly one argument (2 given)

### ISSUE THREAD

**Issue by ronicaa** [novoalab/nanoRMS#14]
Hi, 

When I run ` python /my/path/to/epinano_RMS/epinano_rms.py -R /my/path/to/curlcakes_ref.fasta -b /my/path/to/UNM-rep1.sorted.bam -s epinano_RMS/sam2tsv`, I get this error: 
![image](https://user-images.githubusercontent.com/87814693/130358373-98e30608-1c24-4a00-9652-cc5055114eb1.png)
It seems that write() only takes one string, but you've given it two instead. And my python version is 3.8.8.

Thanks for your help in advance!

**Comment by wvdtoorn** [comment]
Try using `python /my/path/to/epinano_RMS/epinano_rms.py -R /my/path/to/curlcakes_ref.fasta -b /my/path/to/UNM-rep1.sorted.bam -s epinano_RMS/sam2tsv.jar`

**Comment by Huanle** [comment]
Hi @ronicaa ,

thanks for using nanoRMS and thanks @lpryszcz for forwarding the issue.
the error message reminds users to prepare a reference sequences dictionary file using picard's CreateSequenceDictionary subcommand.
But you are right that the syntax is also incorrect. So I have corrected and attached it here. Please let me know if you need further help!
[epinano_rms.py.txt](https://github.com/novoalab/nanoRMS/files/7525457/epinano_rms.py.txt)
---- reminder, please change the file extension to *.py* before using it.

**Comment by nagarkarsanket** [comment]
Hi @Huanle 
I am encountering the same issue as above. I used the corrected file you have attached and the error still persists. 
FYI following are details of the run:

**python my_path/nanoRMS/epinano_RMS/epinano_rms.py -R reference.fasta.dict -b my_path/CT4_sorted.bam -s my_path/nanoRMS/epinano_RMS/sam2tsv.jar
Traceback (most recent call last):
  File "my_path/nanoRMS/epinano_RMS/epinano_rms.py", line 354, in <module>
    main()
  File "my_path/nanoRMS/epinano_RMS/epinano_rms.py", line 263, in main
    sys.stderr.write (args.reference, 'does not exist')
TypeError: write() takes exactly one argument (2 given)**

**Comment by bhargava-morampalli** [comment]
Is this issue resolved for anyone? I am getting the same error and cant get past it.

**Comment by Huanle** [comment]
Hi @nagarkarsanket @bhargava-morampalli ,
It's related to python syntax that is related to python verssion. 
Can you try the one below and let me know whehter it works?
Thanks. 
[epinano_rms.py.txt](https://github.com/novoalab/nanoRMS/files/7893809/epinano_rms.py.txt)

**Comment by bhargava-morampalli** [comment]
Thanks Huanle, 

I tried your modified file and I got another error that's mentioned in another open issues.

`FileNotFoundError: [Errno 2] No such file or directory: './home/share/yuxin/2021Fall/DATA/hm_tmp/HMEC_WT/bam/HMEC_WT_g.tmp_splitted_base_freq.done_splitting'`

I saw that you posted another version of the epinano_RMS.py file there. 
So, I compared the files from my issue and that issue - added changes from file in that issue to my file. 

Now, the epinano_RMS.py runs fine with no issues. 

I don't see any outputs in the folder I am running it from. But, I see some outputs in the bam folder. 

<img width="740" alt="Screenshot 2022-01-19 at 8 59 17 PM" src="https://user-images.githubusercontent.com/20497781/150088929-d8e31964-bf50-49f0-bc88-b0037fa84f46.png">

**Comment by Huanle** [comment]
Hi @bhargava-morampalli ,
I will combine the two edits in one file. Thanks for pointing that out. 
Yes, you are supposed to have results in the same folder where your bam file is saved.

**Comment by nagarkarsanket** [comment]
> Hi @nagarkarsanket @bhargava-morampalli , It's related to python syntax that is related to python verssion. Can you try the one below and let me know whehter it works? Thanks. [epinano_rms.py.txt](https://github.com/novoalab/nanoRMS/files/7893809/epinano_rms.py.txt)

Thanks. Python version change and the syntax version worked for this issue.
